Fix for Negative Repeat Count in Scheduler (#101)
django-q2/django-q2 pull request #146
Opened 2023-12-13 09:58 UTC by Bonekit

Hello Folks,

The line of code s.repeats += -1 in the scheduler function has been commented out. This change is based on the understanding that s.repeats is incorrectly used as a counter for the number of executions of a task, which results in negative values once the task has been executed more times than initially scheduled.

Best Regards
Tobias

2023-12-13 16:29 UTC, GDay requested changes
Thanks for the PR. 

The `repeat` value is actually used to indicate how often a schedule should be repeated. 0 means never, -1 means indefinitely. Anything above 0 gets counted back until it hits 0 and then stops. 

So commenting this line would leave schedules with a positive integer on repeat forever.

Instead, we should check if the value is -1 or below that and then not change change that value. Bonus points for a migration script that would set all schedules with a repeat < -1 back to -1.

2023-12-13 17:31 UTC, Bonekit commented
Hello,

Sorry I have to write with my mobile phone. So my text will be shorter then my first one.

I pushed another fix, this should now fix the already broken repeats with numbers like -3737

Decreasing Numbers should now only affect numbers higher then 0.

2023-12-14 06:02 UTC, Bonekit commented
I checked the tests, it seems something is wrong with a multidict. Gcc failed to build.I will look into it.

2023-12-14 06:09 UTC, Bonekit commented
It seems that gcc is missing to build everything.

error: command 'gcc' failed: No such file or directory

Are you starting the tests from your system or a virtual environment?
Can you check if everything is installed correctly?

2023-12-14 07:37 UTC, Bonekit commented
I executed the tests with docker-compose like described in your project description. 
Everything was running fine:
![Test passed](https://github.com/django-q2/django-q2/assets/12057448/b818e38a-a8fd-49b4-8dc0-f78ce0c032a1)

A few Warnings about deprecated settings, if Django 5 will be used. 
I installed the newest Docker Version and started your Test Script within my Virtual Environment.

2023-12-14 13:43 UTC, GDay commented
Thanks for looking into it. The CI error is not due to your PR. It seems unrelated, looks like it has to do with the coveralls library. In any case, this looks good, will merge it. 

Thanks!

2023-12-14 13:43 UTC, GDay approved these changes

2023-12-14 13:44 UTC, merged